UNDEFINED = 65536
SQUIGGLIFYTAB = 0
BUBBLIFYTAB = 1
LSYSTIFYTAB = 2
GCODETAB = 3
GCODESENDERTAB = 4
LINIFYTAB = 5
RANDWALKTAB = 6

TAB_ORDER = {
    SQUIGGLIFYTAB : 0,
    BUBBLIFYTAB   : 1,
    LSYSTIFYTAB   : 2,
    LINIFYTAB     : 3,
    RANDWALKTAB   : 4,
    GCODETAB      : 5,
    GCODESENDERTAB: 6,
}
