UNDEFINED = 65536
SQUIGGLIFYTAB = 0
BUBBLIFYTAB = 1
LSYSTIFYTAB = 2
GCODETAB = 3
GCODESENDERTAB = 4
LINIFYTAB = 5

TAB_ORDER = {
    SQUIGGLIFYTAB : 0,
    BUBBLIFYTAB   : 1,
    LSYSTIFYTAB   : 2,
    LINIFYTAB     : 3,
    GCODETAB      : 4,
    GCODESENDERTAB: 5
}
