UNDEFINED = 65536
SQUIGGLIFYTAB = 0
BUBBLIFYTAB = 1
LSYSTIFYTAB = 2
GCODETAB = 3
GCODESENDERTAB = 4
LINIFYTAB = 5
RANDWALKTAB = 6
HATCHIFYTAB = 7

TAB_ORDER = {
    SQUIGGLIFYTAB : 0,
    BUBBLIFYTAB   : 1,
    LSYSTIFYTAB   : 2,
    LINIFYTAB     : 3,
    RANDWALKTAB   : 4,
    HATCHIFYTAB   : 5,
    GCODETAB      : 6,
    GCODESENDERTAB: 7,
}
